---
- name: Provision base
  hosts: all

  roles:
  - role: base

- name: Setup a Kubernetes cluster
  hosts: kubernetes_servers

  roles:
  - role: podman

  - role: cri-o

  - role: kubernetes

  - role: metrics-server
