--- 

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack
  tags: load_kernel_modules

- name: Persist kernel modules
  copy:
    src: "ipvs_modules.conf"
    dest: "/etc/modules-load.d/ipvs.conf"
    owner: root
    group: root
  tags: persist_kernel_modules
