---
- name: speed up dnf
  lineinfile: 
    path: "/etc/dnf/dnf.conf"
    state: present
    line: "{{ item }}"
  with_items:
  - "max_parallel_downloads=10"

- name: upgrade all packages
  dnf:
    name: '*'
    state: latest

- name: Install epel
  dnf:
    name: epel-release
    state: latest

- name: Install extras
  dnf:
    name: 
      - "@Development Tools"
      - iproute-tc
      - bind-utils
      - tmux
      - vim
      - htop
      - telnet
      - net-tools
      - tcpdump
      - jq
